# Generated by Django 3.1.7 on 2021-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASISTENCIAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(max_length=120)),
                ('Asistencias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CLASIFICACION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.TextField(max_length=120)),
                ('Puntos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EQUIPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.TextField(max_length=120)),
                ('Jugadores', models.IntegerField()),
                ('EdadMedia', models.IntegerField()),
                ('ValorTotal', models.FloatField()),
                ('ValorMedio', models.FloatField()),
                ('Actualizacion', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FOTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.TextField(max_length=120)),
                ('Nombre', models.TextField(max_length=120)),
                ('LinkFoto', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='GOLEADORES_EQUIPOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.TextField(max_length=120)),
                ('Nombre', models.TextField(max_length=120)),
                ('Goles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GOLES_ENCAJADOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(max_length=120)),
                ('Goles_encajados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JUGADORES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.TextField(max_length=120)),
                ('edad', models.IntegerField()),
                ('pais', models.TextField(max_length=120)),
                ('equipos', models.TextField(max_length=120)),
                ('dorsal', models.IntegerField()),
                ('posicion', models.TextField(max_length=120)),
                ('precio', models.FloatField()),
                ('actualizacion', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='NOTICIAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.TextField(max_length=1000)),
                ('Foto', models.TextField(max_length=1000)),
                ('Contenido', models.TextField(max_length=10000)),
                ('Equipo', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PICHICHI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(max_length=120)),
                ('Goles', models.IntegerField()),
            ],
        ),
    ]
