# Generated by Django 3.1.7 on 2021-04-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESCUDOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.TextField(max_length=1000)),
                ('Link', models.TextField(max_length=1000)),
            ],
        ),
    ]
